import Home from "../assets/home.svg";
import Webinar from "../assets/webinar.svg";
import Billings from "../assets/billing.svg";
import UserManagement from "../assets/usermanage.svg";
import Settings from "../assets/settings.svg";
import fillHome from "../assets/fillHome.svg";
import fillWebinar from "../assets/fillWebinar.svg";
import fillBilling from "../assets/fillBilling.svg";
import fillUserManagement from "../assets/fillUsermanag.svg";
import fillSettings from "../assets/fillSettings.svg";
import scheduleWebinar from "../assets/scheduleWebinar.svg";
import joinWebinar from "../assets/joinWebinar.svg";
import openRecordings from "../assets/openRecordings.svg";
import calendar from "../assets/calendar.svg";
import leftArrow from "../assets/leftArrow.svg";
import rightArrow from "../assets/rightArrow.svg";
import camera from "../assets/camera.svg";
export { Home, Webinar, Billings, UserManagement, Settings, fillHome, fillWebinar, fillBilling, fillUserManagement, fillSettings,scheduleWebinar,joinWebinar,openRecordings,calendar,leftArrow,rightArrow,camera };